### ISSUE TITLE
Build error at meta-webosose/meta-webos/recipes-webos/nodejs-module-webos/nodejs-module-webos-dynaload.bb:do_configure

### ISSUE THREAD

**Issue by tetsu-koba** [webosose/build-webos#7]
Build error at "make webos-image".

```
WARNING: nodejs-module-webos-service-1.0.1-1-r3 do_install: : Installing roles and services files from bitbake is deprecated - use cmake, qmake, etc.
ERROR: nodejs-module-webos-dynaload-3.0.2-1-r4 do_configure: Function failed: do_configure (log file is located at /home/koba/webos/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/nodejs-module-webos-dynaload/3.0.2-1-r4/temp/log.do_configure.25311)
ERROR: Logfile of failure stored in: /home/koba/webos/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/nodejs-module-webos-dynaload/3.0.2-1-r4/temp/log.do_configure.25311
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: Executing shell function do_configure
| gyp info it worked if it ends with ok
| gyp info using node-gyp@0.12.2
| gyp info using node@6.11.2 | linux | x64
| gyp info spawn python
| gyp info spawn args [ '/home/koba/webos/build-webos/BUILD/sysroots/x86_64-linux/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
| gyp info spawn args   'binding.gyp',
| gyp info spawn args   '-f',
| gyp info spawn args   'make',
| gyp info spawn args   '-I',
| gyp info spawn args   '/home/koba/webos/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/nodejs-module-webos-dynaload/3.0.2-1-r4/git/build/config.gypi',
| gyp info spawn args   '-I',
| gyp info spawn args   '/home/koba/webos/build-webos/BUILD/sysroots/x86_64-linux/usr/lib/node_modules/node-gyp/addon.gypi',
| gyp info spawn args   '-I',
| gyp info spawn args   '/home/koba/.node-gyp/6.11.2/common.gypi',
| gyp info spawn args   '-Dlibrary=shared_library',
| gyp info spawn args   '-Dvisibility=default',
| gyp info spawn args   '-Dnode_root_dir=/home/koba/.node-gyp/6.11.2',
| gyp info spawn args   '-Dmodule_root_dir=/home/koba/webos/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/nodejs-module-webos-dynaload/3.0.2-1-r4/git',
| gyp info spawn args   '--depth=.',
| gyp info spawn args   '--generator-output',
| gyp info spawn args   'build',
| gyp info spawn args   '-Goutput_dir=.' ]
| (node:25978) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
| gyp: /home/koba/.node-gyp/6.11.2/common.gypi not found (cwd: /home/koba/webos/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/nodejs-module-webos-dynaload/3.0.2-1-r4/git) while reading includes of binding.gyp
| gyp ERR! configure error
| gyp ERR! stack Error: `gyp` failed with exit code: 1
| gyp ERR! stack     at ChildProcess.onCpExit (/home/koba/webos/build-webos/BUILD/sysroots/x86_64-linux/usr/lib/node_modules/node-gyp/lib/configure.js:337:16)
| gyp ERR! stack     at emitTwo (events.js:106:13)
| gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
| gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
| gyp ERR! System Linux 4.4.0-116-generic
| gyp ERR! command "/home/koba/webos/build-webos/BUILD/sysroots/x86_64-linux/usr/bin/node" "/home/koba/webos/build-webos/BUILD/sysroots/x86_64-linux/usr/bin/node-gyp" "--arch" "arm" "configure"
| gyp ERR! cwd /home/koba/webos/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/nodejs-module-webos-dynaload/3.0.2-1-r4/git
| gyp ERR! node -v v6.11.2
| gyp ERR! node-gyp -v v0.12.2
| gyp ERR! not ok
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /home/koba/webos/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/nodejs-module-webos-dynaload/3.0.2-1-r4/temp/log.do_configure.25311)
ERROR: Task (/home/koba/webos/build-webos/meta-webosose/meta-webos/recipes-webos/nodejs-module-webos/nodejs-module-webos-dynaload.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4390 tasks of which 11 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory
NOTE: Writing buildhistory took: 28.261276721954346 seconds
NOTE: Build completion summary:
NOTE:   do_populate_sysroot: 0.0% sstate reuse(0 setscene, 340 scratch)
NOTE:   do_package_qa: 0.0% sstate reuse(0 setscene, 186 scratch)
NOTE:   do_package: 0.0% sstate reuse(0 setscene, 194 scratch)
NOTE:   do_packagedata: 0.0% sstate reuse(0 setscene, 192 scratch)
NOTE:   do_package_write_ipk: 0.0% sstate reuse(0 setscene, 186 scratch)
NOTE:   do_populate_lic: 0.0% sstate reuse(0 setscene, 432 scratch)

Summary: 1 task failed:
  /home/koba/webos/build-webos/meta-webosose/meta-webos/recipes-webos/nodejs-module-webos/nodejs-module-webos-dynaload.bb:do_configure
Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [webos-image] Error 1
```

/home/koba/.node-gyp/6.11.2/common.gypi is missing. (/home/koba is my home dir.)
This seems root cause. 
There is /home/koba/.node-gyp/6.11.2/
It is automatically generated during build process (because I use a clean new vm instance to build this.) 

```
$ ls -l /home/koba/.node-gyp/6.11.2/
total 8
drwxr-xr-x 3 koba koba 4096 Nov  1  2016 include
-rw-r--r-- 1 koba koba    2 Apr  1 02:07 installVersion
```

**Comment by chbae** [comment]
Please see in http://forum.webosose.org/t/another-build-error/178/13 and we are ready to fix this issue. Thanks

**Comment by tetsu-koba** [comment]
Thank you!

```
sudo rm -rf ~/.node-gyp
make webos-image
```

The build finished and I got SD card image finally.
